"""updated store_number as an integer  metric to models in the  models file

Revision ID: 90698bfe762f
Revises: 0a034ccc6a99
Create Date: 2023-08-09 12:48:15.754156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90698bfe762f'
down_revision: Union[str, None] = '0a034ccc6a99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
